var GAME_LEVELS = [
  ["  x    y y y y y                         y y y y y            y y y y y      x  ",
   "  x        y y y y y                   y y y y           y y y y y           x  ",
   "  x            y y y y y                  y y y y  y y y y y y y      y y y  x  ",
   "  x     y y y y y y                         y y y y            y y y y y     x  ",
   "  x                                                                          x  ",
   "  x                           v z              z              z  z          xx  ",
   "  x                          xxxxxxx           xx             xxxxx          x  ",
   "  x    z                                                                  z  x  ",
   "  x   xxxxx                         x!!xx                                xxxxx  ",
   "  x                                 x!!xx           z                        x  ",
   "  xx                         v      xxxxx         xxxx             z         x  ",
   "  x                        xxxxxxx          xx                    xxxx       x  ",
   "  x           z                                                              x  ",
   "  x          xxx                             z                               x  ",
   "  x                                         xxxxx                 !!!        x  ",
   "  x  z                                                     !!    !xxx!       x  ",
   "  xxxx                                             xx      xx    xx!xx       x  ",
   "  x                   z             o o      xx                 !x!!!x!      x  ",
   "  x                xxxxxx                                        xx!xx       x  ",
   "  x                x               xxxxx                     !!!!!x!x!!!!!   x  ",
   "  x                x                                  !!!          !         x  ",
   "  x                x                      o o                      !         x  ",
   "  x              xxx    o                                          !         x  ",
   "  x              x x                     xxxxx                    !x!      o x  ",
   "  x          xxxxx x    o                                       !!!x!!!      x  ",
   "  x  @       x     x                                             xxxxx       x  ",
   "  xxxxxxxxxxxx     xxxxxxxxxxxx                            xxxxxxx   xxxxxxxxx  ",
   "                              x                            x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "      @       o                  o                                              ",
   "     xxx    xxxx               xxxxxxx        z                                 ",
   "                         o              xxxxxxxxxx!!xx                          ",
   "                      xxxxxx                     xxxxx                          ",
   "               o                                           o   o                ",
   "              xxxx!x                                      xxxxxxx               ",
   "                                                                                ",
   "                 xxxxx!!!!!xxxxxxxx                                             ",
   "                                            v     v                             ",
   "                                       xxxxxxxxxxxxxxx                          ",
   "                                                                 z              ",
   "          o                                                    xxxxx            ",
   "      xxxxxxxxxxxx                !!!!!!                                        ",
   "                                                       v                  xxx   ",
   "                                                  xxxxxxxxx      xx             ",
   "                        v     o                                                 ",
   "                      xxxxxxxxxx                                                ",
   "                                                                      o         ",
   "               v   z                        z                        xxx        ",
   "            xxxxxxxxx                     xxxxxx                   o            ",
   "                                                             xxxxxxxxx          ",
   "                                    o                                           ",
   "                o                xxxxxxx                  z                     ",
   "              xxxxxxxx                                 xxxxxxxxxx               ",
   "                                                                                ",
   "                                    o      o                                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                ",
   "                                       z                                        ",
   "                                   xxxxxx                                       ",
   "          o                              xxx                      o             ",
   "        xxxxxx                                                xxxxxxxx          ",
   "                                                                                ",
   "                                                  o  v  o           o           ",
   "                     v                          xxxxxxxxxxx        xx           ",
   "                   xxxxxx                                                       ",
   "          o                                  v                                  ",
   "         xxx                               xxxxxx                   o      o    ",
   "                               o                                  xxxxxxxxxxxx  ",
   "  @                           xxxxxx                                            ",
   " xxx                                                                            ",
   "         v                                                                      ",
   "        xxxx                                        xxxxxxxxxx                  ",
   "                                     xxxxxxx!!!!!!!!x                           ",
   "                                           xxxxxxxxxx                           ",
   "                      z                                                         ",
   "                   xxxxxxx                 o                                    ",
   "     o                                  xxxxxxx                     o           ",
   "    xxx                                                         xxxxxxxx        ",
   "                 o       o                                                      ",
   "                xxxxxxxxxxxx                                                    ",
   "                                               v    v    v                      ",
   "                                            xxxxxxxxxxxxxxxx     o    v      o  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!                                          !!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!                                                   !!!!!!!!!!!!!!!!!!!!!",
   "!!!                                                              !!!!!!!!!!!!!!!",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                o     v  o o o o o o o o o o o o o  v                           ",
   "        x      xx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         ",
   "                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
   "                                                            o                   ",
   "                                                           xxx      xx          ",
   "          xxx                                                           xx      ",
   "                    xxx                                                         ",
   "                         v                                                      ",
   "                        xxxxx                                  o                ",
   "                                                xx            xx                ",
   "                                                                                ",
   "                               xxx       xx          o                  o       ",
   "                                                     x                  xx      ",
   "                                                                                ",
   "                                                 v              o               ",
   "                                                xxx             xx              ",
   "                                            o                                   ",
   "                              o          xxxxx                                  ",
   "       @     v               xxx                                     v        o ",
   "      xxxxxxxxxx                                                    xxx      xx ",
   "                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["x                                                                              x",
   "x              y         y        yyyyy        y    y                          x",
   "x               y       y        y     y       y    y                          x",
   "x                y     y        y       y      y    y                          x",
   "x                 y   y         y       y      y    y                          x",
   "x                  y y          y   o   y      y    y                          x",
   "x                   y           y       y      y    y                          x",
   "x                   y            y     y       y    y                          x",
   "x                   y             y   y        y    y                          x",
   "x                   y              yyy         yyyyyy                          x",
   "x                                                                              x",
   "x                  y                   y    y    yy      y    y                x",
   "x                   y                 y     y    y y     y    y                x",
   "x       y   y        y       y       y      y    y  y    y    y                x",
   "x       y   y         y     y y     y       y    y   y   y    y                x",
   "x     y       y        y   y   y   y        y    y    y  y    y                x",
   "x      y     y          y y     y y         y    y     y y                     x",
   "x       yyyyy            y       y          y    y      yy    y                x",
   "x  @                                                                           x",
   "x                                                                              x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
